// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdJ0sVuN9ve993C_2-WxmCaAQmJfWG-B8',
    appId: '1:921591914517:web:84fe70ec47995803e5ee1c',
    messagingSenderId: '921591914517',
    projectId: 'datn-7d37e',
    authDomain: 'datn-7d37e.firebaseapp.com',
    storageBucket: 'datn-7d37e.firebasestorage.app',
    measurementId: 'G-1H0NLZBY4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-__ort6vzZJ365QSn7E1GTdBaCeLy88c',
    appId: '1:921591914517:android:354422315e2bfdafe5ee1c',
    messagingSenderId: '921591914517',
    projectId: 'datn-7d37e',
    storageBucket: 'datn-7d37e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp-yQsuoOXOcw_WllGXD-sjfaESZGti-o',
    appId: '1:921591914517:ios:9cdf82e4ad37e364e5ee1c',
    messagingSenderId: '921591914517',
    projectId: 'datn-7d37e',
    storageBucket: 'datn-7d37e.firebasestorage.app',
    iosBundleId: 'com.example.robotDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp-yQsuoOXOcw_WllGXD-sjfaESZGti-o',
    appId: '1:921591914517:ios:9cdf82e4ad37e364e5ee1c',
    messagingSenderId: '921591914517',
    projectId: 'datn-7d37e',
    storageBucket: 'datn-7d37e.firebasestorage.app',
    iosBundleId: 'com.example.robotDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdJ0sVuN9ve993C_2-WxmCaAQmJfWG-B8',
    appId: '1:921591914517:web:e70a6cd5d13c2bffe5ee1c',
    messagingSenderId: '921591914517',
    projectId: 'datn-7d37e',
    authDomain: 'datn-7d37e.firebaseapp.com',
    storageBucket: 'datn-7d37e.firebasestorage.app',
    measurementId: 'G-341QHFSEY8',
  );
}
